
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.Scanner;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aymen
 */
public class EmprunteurFrame extends javax.swing.JFrame {
    /**
     * Creates new form EmprunteurFrame
     */
    public EmprunteurFrame() {
        initComponents();
        
        bonjourLabel.setText("Bonjour, "+Login.utilisateur.getPrenom()+" "+Login.utilisateur.getNom()+" !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boutonReserver = new javax.swing.JButton();
        boutonEmprunter = new javax.swing.JButton();
        boutonRetourner = new javax.swing.JButton();
        boutonReserverLivre = new javax.swing.JButton();
        boutonConsulterCatalogue = new javax.swing.JButton();
        boutounVoirHistorique = new javax.swing.JButton();
        bonjourLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        boutonDeconnection = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boutonReserver.setBackground(new java.awt.Color(0, 0, 0));
        boutonReserver.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        boutonReserver.setForeground(new java.awt.Color(255, 255, 255));
        boutonReserver.setText("Reserver un livre");
        boutonReserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonReserverActionPerformed(evt);
            }
        });

        boutonEmprunter.setBackground(new java.awt.Color(0, 0, 0));
        boutonEmprunter.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        boutonEmprunter.setForeground(new java.awt.Color(255, 255, 255));
        boutonEmprunter.setText("Emprunter un livre");
        boutonEmprunter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEmprunterActionPerformed(evt);
            }
        });

        boutonRetourner.setBackground(new java.awt.Color(0, 0, 0));
        boutonRetourner.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        boutonRetourner.setForeground(new java.awt.Color(255, 255, 255));
        boutonRetourner.setText("Retourner un livre");
        boutonRetourner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonRetournerActionPerformed(evt);
            }
        });

        boutonReserverLivre.setBackground(new java.awt.Color(0, 0, 0));
        boutonReserverLivre.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        boutonReserverLivre.setForeground(new java.awt.Color(255, 255, 255));
        boutonReserverLivre.setText("Rechercher un livre");
        boutonReserverLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonReserverLivreActionPerformed(evt);
            }
        });

        boutonConsulterCatalogue.setBackground(new java.awt.Color(0, 0, 0));
        boutonConsulterCatalogue.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        boutonConsulterCatalogue.setForeground(new java.awt.Color(255, 255, 255));
        boutonConsulterCatalogue.setText("Consulter le catalogue");
        boutonConsulterCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonConsulterCatalogueActionPerformed(evt);
            }
        });

        boutounVoirHistorique.setBackground(new java.awt.Color(0, 0, 0));
        boutounVoirHistorique.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        boutounVoirHistorique.setForeground(new java.awt.Color(255, 255, 255));
        boutounVoirHistorique.setText("Voir votre historique");
        boutounVoirHistorique.setActionCommand("");
        boutounVoirHistorique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutounVoirHistoriqueActionPerformed(evt);
            }
        });

        bonjourLabel.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        bonjourLabel.setText("Bonjour, Aymen Belhadj!");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Que voulez vous faire ?");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Annuler reservation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        boutonDeconnection.setBackground(new java.awt.Color(153, 153, 153));
        boutonDeconnection.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boutonDeconnection.setText("Se déconnecter");
        boutonDeconnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDeconnectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bonjourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(boutonDeconnection))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(boutonReserverLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boutonConsulterCatalogue)
                                .addGap(428, 428, 428)
                                .addComponent(boutounVoirHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 160, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boutonEmprunter, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(boutonRetourner, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(boutonReserver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boutonConsulterCatalogue, boutonEmprunter, boutonReserver, boutonReserverLivre, boutonRetourner, boutounVoirHistorique, jButton1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(bonjourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(boutonDeconnection, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonRetourner)
                    .addComponent(boutonEmprunter)
                    .addComponent(boutonReserver, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonReserverLivre)
                    .addComponent(boutonConsulterCatalogue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutounVoirHistorique))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {boutonConsulterCatalogue, boutonEmprunter, boutonReserver, boutonReserverLivre, boutonRetourner, boutounVoirHistorique, jButton1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonEmprunterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEmprunterActionPerformed
        new EmprunterLivreFrame().setVisible(true);
    }//GEN-LAST:event_boutonEmprunterActionPerformed

    private void boutonReserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonReserverActionPerformed
        new ReserverFrame().setVisible(true);
    }//GEN-LAST:event_boutonReserverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AnnulerReservation().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boutonRetournerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonRetournerActionPerformed
        new RetournerFrame().setVisible(true);
    }//GEN-LAST:event_boutonRetournerActionPerformed

    private void boutonConsulterCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonConsulterCatalogueActionPerformed
        new ConsulterLeCatalogue().setVisible(true);
    }//GEN-LAST:event_boutonConsulterCatalogueActionPerformed

    private void boutounVoirHistoriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutounVoirHistoriqueActionPerformed
        new Historique().setVisible(true);
    }//GEN-LAST:event_boutounVoirHistoriqueActionPerformed

    private void boutonReserverLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonReserverLivreActionPerformed
        new RechercherLivre().setVisible(true);
    }//GEN-LAST:event_boutonReserverLivreActionPerformed

    private void boutonDeconnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDeconnectionActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_boutonDeconnectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmprunteurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmprunteurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmprunteurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmprunteurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmprunteurFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonjourLabel;
    private javax.swing.JButton boutonConsulterCatalogue;
    private javax.swing.JButton boutonDeconnection;
    private javax.swing.JButton boutonEmprunter;
    private javax.swing.JButton boutonReserver;
    private javax.swing.JButton boutonReserverLivre;
    private javax.swing.JButton boutonRetourner;
    private javax.swing.JButton boutounVoirHistorique;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}